### ISSUE TITLE
Bug: typing horizontally way

### ISSUE THREAD

**Issue by Rodielm** [jmjuanes/folio#16]
### Describe the issue

When typing it should be expanded horizontally way by default.

### To reproduce

1. Click Text
2. Click on the board
3. Type whatever you one

Preview
![typeText-2023-04-09_21 15 30](https://user-images.githubusercontent.com/10471758/230792393-9271219d-1c14-4828-8e58-d3921426394d.gif)

Expected
![typeText_1-2023-04-09_21 19 20](https://user-images.githubusercontent.com/10471758/230792471-3db308ce-449d-4e53-80ba-ba0beca3bf0b.gif)

### What browser(s) are you seeing the problem on?

Chrome

**Comment by jmjuanes** [comment]
Hi @Rodielm. The text element in Folo works in a different way than in Excalidraw: the width of the text element is always fixed by the user, and the height is based on the text content.   

The problem there is that you are adding a new text element, but instead of dragging the text box for specifying the width you want, you are releasing the left button of the mouse, and the text box has a very small width. To fix that, I am going to specify an initial width of the text box, so:
- If you add a text element without dragging, the text box will have an initial width of `400px`.
- If you add a text box with dragging, it will have the with of the dragged area.

**Comment by jmjuanes** [comment]
Fixed in commit https://github.com/jmjuanes/folio/commit/d3572ba95ec4d2aefbdb70f1e6013b7f799784ff 

![Peek 2023-04-20 20-34](https://user-images.githubusercontent.com/5751201/233457000-f47bd5b8-bcc5-4524-9d59-3721cdeca687.gif)
